# This is a basic workflow to help you get started with Actions

name: Test 1

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
#     paths: 
#       - schema_change_detection/*
#       - table_creates_and_drops_log/*
#       - workflows/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Treasure Workflow 1
      uses: max-abe-king/td-wf-actions@v0.0.8
      with:
        td_master_apikey: ${{ secrets.td_master_apikey }}
        td_wf_project_name: mk_git_test_1
        github_path: workflows/schema_change_detection
        
#     - name: Treasure Workflow 1
#       uses: toru-takahashi/treasure-workflow-actions@v0.0.2
#       with:
#         td_master_apikey: ${{ secrets.td_master_apikey }}
#         td_wf_project_name: mk_git_test_1 --project workflows/table_creates_and_drops_log -r "$(date +%Y-%m-%dT%H:%M:%S%z)"-"$(git show --pretty | head -n 1)"
